<?php

// Definitions used by all scripts

$DIR = dirname(__DIR__) . DIRECTORY_SEPARATOR ;

$SCRIPT_DIR = $DIR . 'script' . DIRECTORY_SEPARATOR;
$INCLUDE_DIR = $DIR . 'include' . DIRECTORY_SEPARATOR;
$CONFIG_DIR = $INCLUDE_DIR. 'config'. DIRECTORY_SEPARATOR;
$FUNCTION_DIR = $INCLUDE_DIR .'function'. DIRECTORY_SEPARATOR;
$CLASS_DIR = $INCLUDE_DIR . 'class'. DIRECTORY_SEPARATOR;
$TEMPLATE_DIR = $DIR. 'template'. DIRECTORY_SEPARATOR;
$NEXUS_DIR = $TEMPLATE_DIR. 'nexus'. DIRECTORY_SEPARATOR;

?>
